# Categories
CATEGORY_GRAMMAR = "Grammar"
CATEGORY_READING = "Reading"
CATEGORY_LISTENING = "Listening"
CATEGORIES = [CATEGORY_GRAMMAR, CATEGORY_READING, CATEGORY_LISTENING]

# Difficulties
DIFFICULTY_EASY = "Easy"
DIFFICULTY_MEDIUM = "Medium"
DIFFICULTY_HARD = "Hard"
DIFFICULTIES = [DIFFICULTY_EASY, DIFFICULTY_MEDIUM, DIFFICULTY_HARD]

# Question Statuses
STATUS_DRAFT = "Draft"
STATUS_ACTIVE = "Active"
STATUS_INACTIVE = "Inactive"
STATUS_ARCHIVED = "Archived"
STATUSES = [STATUS_DRAFT, STATUS_ACTIVE, STATUS_INACTIVE, STATUS_ARCHIVED]

# Question Options
OPTION_KEYS = ["A", "B", "C", "D"]
